image: 'node:lts-alpine'

stages:
  - build
  - test
  - deploy

# These folders are cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    # Default cache directory from https://classic.yarnpkg.com/en/docs/install-ci/#gitlab.
    - node_modules/
    # Cache Next.js build
    - .next
    - build/

build:
  stage: build
  script:
    # Install via yarn with frozen-lockfile to allow reproducible dependencies and
    # check-files option to check if the node_modules cache is valid.
    - yarn install --frozen-lockfile --check-files --non-interactive
    - yarn build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID

test:
  stage: test
  needs:
    - build
  script:
    - yarn lint
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID

pages:
  stage: deploy
  variables:
    FF_USE_FASTZIP: 'true'
    ARTIFACT_COMPRESSION_LEVEL: 'fastest'
  needs:
    - build
    - test
  script:
    - mv public .public
    - cp -r build public
    - gzip -k -9 $(find public -type f)
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
